sudo: required
language: rust

# Cache cargo symbols for faster build
cache: cargo

# run builds for all the trains (and more)
rust:
  - nightly
  - beta
  # check it compiles on the latest stable compiler
  - stable

# the main build
script:
  - |
    cargo build --verbose &&
    cargo test --verbose &&
    cargo bench --verbose &&
    cargo doc --verbose
