sudo: required
language: rust
cache: cargo
rust:
  - nightly
script:
  - |
    cargo build --verbose &&
    cargo test --verbose &&
    cargo bench --verbose &&
    cargo doc --verbose
env:
  global:
    - secure: aeDjDkv3yHDovX8iAIlPSUwc9AvvgS8YTxshlCVEpjjb3gIOzYAYlAz3d6zDPJP5cvpCbySA8cV2nOXjur/uSUDDE0LekIqO0BvdL8lYs/ElmFXV/KKNYWcNZEOPbt/mUEw5bBZn/3QNcJa/Y/usJAZZBfD1kJObGfp1EFD+lLhWVraAvsjf45MNrNbdoOWJUMQqs1aJ3XO1TUpMKnfSRau/vW656ZagO3toc7+M/WRtzk6kJSkgokOUd9N5ojwn6fmpY27Ml3wbFXm/AXsPrm5FGgKuF5Q4V1UAf9x/DEzkWSlad982JaqolbLX4qBkR02/akte6yAECBUhkM5JDMVzsnAlu0QggQwjOcSzZxUVndKlYMd70gfrjwcU6r2BZ8koU4vxQgQsBM2a3Ah7TRZaWgz/G55JVOmk5uGf+uvKi7LbK5clYMGs4VmpDyKBE+OoL6P2qiiWaD3/QMtzROubkUADZWHXPhC3AJRvB/eTf3enZRJD12sR1+Quwp4/UjcqjQ2Aw9jDgfSN7n+gnB9gtSrOzuisEpfqzMM5M9j5jDKTKVmcR7zVV9FY5sKgZPJDAB+UDoLpnlvUWlD8Fh1JETqGKSlyJZujHJzj8gWiNCFf7iQvzd/MyXHAkEPsFnT8NdTqrf86ahlDxaMF+XkpTCa8Jfgp6BDQ1tZGAoA=
after_success:
  - openssl aes-256-cbc -K $encrypted_871d352bed27_key -iv $encrypted_871d352bed27_iv
    -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - chmod 600 .travis/id_rsa
  - ssh-keyscan ${DEPLOY_HOST} >> $HOME/.ssh/known_hosts
  - sftp -i .travis/id_rsa travisci@${DEPLOY_HOST}:deploy <<< $'put target/debug/DemoArigatoMrRobto'
