[package]
name = "demo_arigato_mr_roboto"
version = "0.1.0"
authors = ["Quoc-Anh Vu <quoc.v.anh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
